name: Update submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules to latest commit on tracked branches
        run: |
          git submodule update --remote

      - name: Commit updated submodules (if needed)
        env:
          PUSH_TOKEN: ${{ secrets.BREVLY_REPO_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: update submodules to latest commit"
            git push https://x-access-token:$PUSH_TOKEN@github.com/miguelriosoliveira/brev.ly.git
          else
            echo "No submodule updates to commit."
          fi
